# This is a static gempsec automatically generated by rake.  It's better to
# edit the Rakefile than this file.  It is kept in the repository for the
# benefit of github.

spec = Gem::Specification.new { |s|
	s.platform = "ruby"
	s.author = "Pete Elmore"
	s.email = "1337p337@gmail.com"
	s.files = ["lib/senga.rb", "doc/LICENSE", "doc/README", "doc/TODO", "Rakefile"]
	s.require_path = "lib"
	s.has_rdoc = true
	s.extra_rdoc_files = ["doc/LICENSE", "doc/README", "doc/TODO"]
	s.extensions = []
	s.executables = []
	s.name = "senga"
	s.summary = "Senga draws lines.  Simplest graphing library."
	s.homepage = "http://github.com/pete/senga"
	s.version = "0.1.0"
	s.add_dependency "rmagick", ">= 0"
}

Gem::Builder.new(spec).build if __FILE__ == $0
